### ISSUE TITLE
Where is the Pytorch based implementation?

### ISSUE THREAD

**Issue by Hellomodo** [ashwhall/dsnt#1]
Hi @ashwhall !
     Thanks for your great work!
     I have read your paper "Numerical Coordinate Regression with Convolutional Neural Networks", and I remember it said in your paper that your code is "written in PyTorch, and is available online". 
     I am more familiar with PyTorch, so can you help me with a PyTorch version of your code? That will also help me a lot with my own work .

**Comment by ashwhall** [comment]
Hi @Hellomodo , the unofficial Pytorch implementation by the paper's author @anibali can be found here: https://github.com/anibali/dsntnn

Happy to hear you're a fan of his work!
